sonar.projectKey=PayReconcile
sonar.organization=prachiBarhate23
sonar.projectName=PayReconcile Frontend

# Source directory
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/.dist/**,**/dist/**,**/*.test.tsx,**/*.spec.tsx

# TypeScript-specific settings
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Encoding
sonar.sourceEncoding=UTF-8
